services:
  main:
    image: "docker:26.0.0-dind"
    volumes:
      - .:/workspace:cached
    tty: true
    privileged: true
  mock:
    image: "mcr.microsoft.com/devcontainers/base:jammy"
    volumes:
      - .:/workspace:cached
    tty: true
  runner:
    image: "docker:26.0.0-dind"
    volumes:
      - .:/workspace:cached
    tty: true
    privileged: true
